CREATE TABLE WALLETS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULLNAME VARCHAR(100),
    CPF BIGINT,
    EMAIL VARCHAR(100),
    "PASSWORD" VARCHAR(100),
    "TYPE" INT,
    BALANCE DECIMAL(10, 2)
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (CPF);
CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

CREATE TABLE TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYER INT,
    PAYEE INT,
    AMOUNT DECIMAL(10, 2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES WALLETS(ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS(ID)
);
